### ISSUE TITLE
Draft URL Structure (WIP)

### ISSUE THREAD

**Issue by jnmarcus** [caciviclab/disclosure-frontend#110]
`/state` - CA state data
`/state/{electionYear-Month(?)}`
`/state/{electionYear-Month(?)}/proposition`

`/cities` - all cities in CA with (& without?)data

`/city/{cityId}/{cityName}` - a city page
`/city/{cityId}/{cityName}/{electionYear-Month(?)}`
`/city/{cityId}/{cityName}/{electionYear-Month(?)}/{position}` - overview data for all candidates running for one position in a given election year
`/city/{cityId}/{cityName}/{electionYear-Month(?)}/{position}/candidate/{candidateId}/{candidateName}` - for a given election only.  will most likely link back to a general 'profile' page for the candidate with info on all elections he/she has run in(?)
`/city/{cityId}/{cityName}/{electionYear-Month(?)}/measure/{measureId}`
`/city/{cityId}/{cityName}/{electionYear-Month(?)}/measure/{measureId}/contributors`

`/candidate` - doesn't resolve
`/candidate/{candidateId}/{candidateName}` - candidate 'profile' page for any/all elections, city/county/or state level (??)

**Comment by tdooner** [comment]
As we just discussed, adjusting these endpoints to more closely match the API structure will make the client code a lot simpler.

For example: using `/locality/{localityId}` instead of the city/state prefix will allow for the API client to simply request the API endpoint with the same ID rather than having to resolve the city name back into a locality ID or something.

This comes at the expense of SEO -- your endpoints will definitely have better SEO -- but that is pretty low on our priority list.

As for `/candidate`, it seems redundant to me to have both the `{candidateId}` and `{candidateName}` in the URL

**Comment by KyleW** [comment]
Closing this since I think it's no longer relevant.
