### ISSUE TITLE
Ballot measure contributions calculation looks off

### ISSUE THREAD

**Issue by sfdoran** [caciviclab/disclosure-frontend#251]
[document (17).pdf](https://github.com/caciviclab/disclosure-frontend/files/1140836/document.17.pdf)

@tdooner @mikeubell filing shows $10,745,941.73 total contributions - site shows $13,839,546.

http://www.opendisclosure.io/#!/city/2/oakland/2016/referendum/1/sugar-sweetened-beveragetax

**Comment by mikeubell** [comment]
I see at least one duplicate contribution on the contributions page of 1,554,290.  Maybe we are not filtering 24hr reports properly.

**Comment by mikeubell** [comment]
@sfdoran @tdooner This is really a backend issue.
I think this may be caused by descripancies in filings between the schedule 6 and the 497.  Here are the 497 records for Measure HH:
Filer_ID | Tran_Amt1 | Tran_NamF |  Tran_NamL   | Tran_Date  |  Tran_ID   
----------+-----------+-----------+--------------+------------+------------
 1381041  |      1500 |           | CHEZ PANISSE | 2016-08-30 | NON272
 1381041  |   1525030 | MICHAEL   | BLOOMBERG    | 2016-10-26 | F497P1-440
 1381041  |   1556290 | MICHAEL   | BLOOMBERG    | 2016-11-01 | F497P1-450
 1381041  |     15000 | MICHAEL   | BLOOMBERG    | 2016-11-07 | F497P1-453

Here are Schedule C records over 1000000
 Filer_ID | Tran_Amt1 | Tran_NamL | Tran_Date  | Tran_ID 
----------+-----------+-----------+------------+---------
  1381041 |   1600030 | BLOOMBERG | 2016-10-26 | C440
  1381041 |   1554290 | BLOOMBERG | 2016-11-01 | C450
  1381041 | 1362093.5 | BLOOMBERG | 2016-10-12 | C418
  1381041 |   1348738 | BLOOMBERG | 2016-10-19 | C433

Note the records for 2016-10-26 and  2016-11-01.  We delete duplicates either based on the Tran_ID or the date/amount.  Since the amount recorded on schedule C differs from the amount on 497 these amounts will be counted twice.  Should they file an amended 497 or is ok to just file a schedule C to correct the amount?

**Comment by sfdoran** [comment]
I will look into the amendment issue, but maybe we should think of another way to avoid the duplicates because even if they are required to file an amended 24-hour report if rely on that there will still be times when time lags cause the calculations on OD to be way off.

**Comment by mikeubell** [comment]
I think we would have to change our way of invalidating the 24-hour report to do it by detecting a follow on A/C schedule that supersedes it, rather doing it by the contents of the record.  Or we can assume assume the format of the Trans_id is meaningful and try to parse it.

**Comment by sfdoran** [comment]
I was thinking along those lines - not counting 24-reports if there is an 460 deadline after. That would also take care of another possible scenario - if a committee removes a transaction previously reported on Form 497, they do not amend the 497, they only correct the 460 or 461. So, that would be another time that our calculations would be off. FYI - same issues apply with 496 & 461 reporting.

**Comment by mikeubell** [comment]
Its not just a deadline, but they have to have filed the form… I imagine folks are late sometimes.

**Comment by sfdoran** [comment]
We are talking about total_contributions_calculator.rb, right? I will look and ponder...

**Comment by mikeubell** [comment]
Actually we preprocess the database at load time.  It's in remove_duplicate_trahsactions.sh.

**Comment by mikeubell** [comment]
@sfdoran I'm finding other data that is in 496 forms that our current scheme is not removing.  I can't seem to find anything corresponding in the subsequent Schedules A/B/C/D/E.  For example this for the measure G committee:
 Filer_ID |                  Enty_NamL                   |  Rpt_Date  | Rec_Type | Form_Type | Amount 
----------+----------------------------------------------+------------+----------+-----------+--------
 1345259  | Chris Jackson for Oakland School Board       | 2016-11-04 | S497     | F497P2    |   4264
 1345259  | Kharyshi Wiginton for School                 | 2016-11-04 | S497     | F497P2    |   4264
 1345259  | Lang                                         | 2016-11-04 | S497     | F497P2    |   4264
 1345259  | Mike Hutchinson for School Board 2016        | 2016-11-04 | S497     | F497P2    |   4264
 1345259  | Roseann Torres for Oakland School Board 2016 | 2016-11-04 | S497     | F497P2    |   4264

Do you think these should get ignored, since everyone should have filed their final statements by now?

**Comment by sfdoran** [comment]
I'll check it out and get back.

**Comment by mikeubell** [comment]
There is also this one:
1381041  | COALITION FOR HEALTHY OAKLAND CHILDREN                                     | 2016-08-31 |    1500 | NON272       | CHEZ PANISSE
The amount is too high?, I am guessing rather than issuing a reversal transaction they just dropped it from the later Schedule A.  I don't see a txn from Chez Panisse on a Schedule A.

**Comment by sfdoran** [comment]
I'll do the calculations on my end and let's talk at hack night.

**Comment by sfdoran** [comment]
Okay. I'll share what I come up with here by hack night.

**Comment by mikeubell** [comment]
I have moded his to disclosure-backend-static #73

**Comment by mikeubell** [comment]
I have moved this to disclosure-backend-static-#73
