### ISSUE TITLE
PLACEHOLDER Main user flow for search box

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-frontend#56]
This is a placeholder story, @sseiter can you tackle this (or assign as appropriate)? @jnmarcus mentioned that the search text is supposed to work differently than we're building it. This isn't critical, but good to document/implement sooner.

## Current behavior (search-style)

The current behavior is that we start with a search box, no results. Typing will match city names against known (supported) cities and jurisdictions. Clicking on a result will take you to the jurisdiction page. i.e.

```
No results -> type in search input -> Show results matching search input
```

## Option A  (filter-style)

This is how @jnmarcus described how this is supposed to work (please correct me if this isn't correct). We start with a search box AND a list of supported cities and jurisdictions. Typing in the search box actually filters the list to only those matching the search input. i.e.

```
All results -> type in search input -> Show fewer results; matching search input
```

**Comment by adborden** [comment]
cc @tdooner

**Comment by amandaric** [comment]
The end goal is to have a flexible search tool that could provide results for the following queries: cities, counties, ballot measures, candidates, and contributors. We can start with a smaller chunk of this list and eventually build it out.

**Comment by amandaric** [comment]
[Main User Flow for Search Bar.pdf](https://github.com/caciviclab/disclosure-frontend/files/185338/Main.User.Flow.for.Search.Bar.pdf)

Attaching wireframe that details the expected behavior of the search bar on the home page. To summarize for the first release, we'd like to provide autosuggestion based on the user's search entry (beginning with the first character entered). It would be great to bold the matching character(s). Let me know if you have any questions!

**Comment by KyleW** [comment]
Is there still work to do here? Seems done to me.

**Comment by tdooner** [comment]
Me too.
