### ISSUE TITLE
Content for FAQ page

### ISSUE THREAD

**Issue by elinaru** [caciviclab/disclosure-frontend#8]
A good start: http://www.opendisclosure.io/faq#

**Comment by evanwolf** [comment]
https://github.com/caciviclab/disclosure-frontend-alpha/blob/master/faq.md

**Comment by evanwolf** [comment]
Perhaps a separate "Glossary" page?

**Comment by adborden** [comment]
I vote no glossary. IMHO, there is another (separate) CA Civic Lab project which I would call "The California Campaign Finance Wiki" which could house the glossary and other information about how campaign finance works in California. And [this](https://github.com/caciviclab/caciviclab.github.io/wiki/Campaign-Finance) is the beginning of that (and it has a [glossary](https://github.com/caciviclab/caciviclab.github.io/wiki/Glossary) already).

**Comment by elinaru** [comment]
So, you're advocating for the FAQ to be at the CCL level and include  the glossary?

**Comment by tdooner** [comment]
I never liked the FAQ page on Open Disclosure. I've seen it allow us to use sloppy design elsewhere -- because the FAQ is a a junk drawer that we can fill with all the technical nitty gritty we decide we can omit a description from the page containing a term. Who reads FAQ's anyway? If somebody is expected to read the FAQ to understand why numbers don't add up, or what a term means, then we have failed that user.

I think it's fine to have some meta-information on an FAQ page, like the first four on http://www.opendisclosure.io/faq. But we need to take care to avoid using it as a place to put useful explanations, for those should be incorporated into the designs of the pages with those explanations.

Perhaps putting the FAQ at the CCL level would force this separation upon us.

**Comment by sseiter** [comment]
The new FAQ page merges the "about us" and the "about this project" and a few FAQs.

**Comment by tdooner** [comment]
@bayreporta just mentioned [OpenSecrets' methodology pages](https://www.opensecrets.org/industries/methodology.php) as an example of a good piece of background for campaign finance discussion.

This led us into a dark rabbit hole where we discussed the distinction between methodology and FAQ, and the possible scenario of having both of those pages.

Ultimately, I think it is important to disclose our methodology, but the format of it does not matter to me. As such, we should figure out all the stuff we want to have either on the "FAQ" or "Methodology" page, and we'll sort out the page layout/names later.

**Comment by adborden** [comment]
Adding @sfdoran here. There is a new draft in progress https://docs.google.com/document/d/1D3MsBqoGi5j_ffhpBsw88S5jhgIFI3i02m93ny1u3aI/edit
